dependents:
  - "bot-boilerplate"

files:
  - ".gitignore"

  # Do not sync the workflow files
  - "!.github/workflows/template-sync.yml"
  - "!.github/template-sync.yml"

  # Do not sync dependabot config
  - "!.github/dependabot.yml"
